In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import warnings
warnings.filterwarnings('ignore')

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)  
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', None)

In [3]:
df = pd.read_csv('odi_ball_by_ball.csv')
match_df = pd.read_csv('odi_match_by_match.csv')

In [4]:
df = df.drop(['Unnamed: 0'],axis=1)

In [5]:
match_df = match_df.drop(['Unnamed: 0'],axis=1)

In [6]:
df.head()

   match_id        date  inning_no batting_team  over_num  balls     batsmen     bowler non_striker  batsmen_runs  extra_runs     extra_type wicket_type player_out fielder  total_runs  is_wicket
0         1  2002-12-29          1  New Zealand         0      1  SP Fleming  J Srinath    NJ Astle             0           1        legbyes           0          0       0           1          0
1         1  2002-12-29          1  New Zealand         0      2    NJ Astle  J Srinath  SP Fleming             0           0  fair delivery           0          0       0           0          0
2         1  2002-12-29          1  New Zealand         0      3    NJ Astle  J Srinath  SP Fleming             0           0  fair delivery           0          0       0           0          0
3         1  2002-12-29          1  New Zealand         0      4    NJ Astle  J Srinath  SP Fleming             1           0  fair delivery           0          0       0           1          0
4         1  2002-12-29          1  New Zealand         0      5  SP Fleming  J Srinath    NJ Astle             0           0  fair delivery           0          0       0           0          0

In [7]:
match_df.head()

   match_id        date                 event_name match_type gender          city                        venue  overs       team_1       team_2  toss_winner toss_decision match_winner player_of_match  by_runs  by_wickets      umpire_1    umpire_2  tv_umpire reserve_umpire  match_refree
0         1  2002-12-29  India tour of New Zealand        ODI   male        Napier          McLean Park, Napier     50  New Zealand        India        India         field  New Zealand        V Sehwag     35.0         NaN  EAR de Silva    DB Cowie  BF Bowden            NaN  RS Madugalle
1         2  2003-01-01  India tour of New Zealand        ODI   male  Christchurch   Jade Stadium, Christchurch     50        India  New Zealand        India           bat  New Zealand       DR Tuffey      NaN         5.0  EAR de Silva    DB Cowie    AL Hill            NaN  RS Madugalle
2         3  2003-01-04  India tour of New Zealand        ODI   male    Queenstown      Davies Park, Queenstown     50        India  New Zealand  New Zealand         field  New Zealand        AR Adams      NaN         7.0  EAR de Silva    DB Cowie    AL Hill            NaN  RS Madugalle
3         4  2003-01-08  India tour of New Zealand        ODI   male    Wellington  Westpac Stadium, Wellington     50  New Zealand        India  New Zealand           bat        India          Z Khan      NaN         2.0     BF Bowden   DJ Harper   DB Cowie            NaN  RS Madugalle
4         5  2003-01-09                  VB Series        ODI   male        Sydney        Sydney Cricket Ground     50    Sri Lanka    Australia    Australia         field    Sri Lanka   ST Jayasuriya     79.0         NaN     RB Tiffin  SJA Taufel    DB Hair            NaN      CH Lloyd

In [8]:
total_df = df.merge(match_df, on=['match_id', 'date'], how='right')

In [9]:
total_df["dots"]=total_df["batsmen_runs"].apply(lambda x: 1 if x==0 else 0) 
total_df["ones"]=total_df["batsmen_runs"].apply(lambda x: 1 if x==1 else 0)
total_df["twos"]=total_df["batsmen_runs"].apply(lambda x: 1 if x==2 else 0)
total_df["threes"]=total_df["batsmen_runs"].apply(lambda x: 1 if x==3 else 0)
total_df["fours"]=total_df["batsmen_runs"].apply(lambda x: 1 if x==4 else 0)
total_df["sixes"]=total_df["batsmen_runs"].apply(lambda x: 1 if x==6 else 0)

In [10]:
total_df.head(1)

   match_id        date  inning_no batting_team  over_num  balls     batsmen     bowler non_striker  batsmen_runs  extra_runs extra_type wicket_type player_out fielder  total_runs  is_wicket                 event_name match_type gender    city                venue  overs       team_1 team_2 toss_winner toss_decision match_winner player_of_match  by_runs  by_wickets      umpire_1  umpire_2  tv_umpire reserve_umpire  match_refree  dots  ones  twos  threes  fours  sixes
0         1  2002-12-29          1  New Zealand         0      1  SP Fleming  J Srinath    NJ Astle             0           1    legbyes           0          0       0           1          0  India tour of New Zealand        ODI   male  Napier  McLean Park, Napier     50  New Zealand  India       India         field  New Zealand        V Sehwag     35.0         NaN  EAR de Silva  DB Cowie  BF Bowden            NaN  RS Madugalle     1     0     0       0      0      0

In [11]:
inn_runs = pd.DataFrame(total_df.groupby(['batsmen','match_id'])['batsmen_runs'].sum()).reset_index()

In [12]:
inn_Ones=pd.DataFrame(total_df.groupby(['batsmen','match_id'])["ones"].sum()).reset_index()
inn_Twos=pd.DataFrame(total_df.groupby(['batsmen','match_id'])["twos"].sum()).reset_index()
inn_Threes=pd.DataFrame(total_df.groupby(['batsmen','match_id'])["threes"].sum()).reset_index()
inn_Fours=pd.DataFrame(total_df.groupby(['batsmen','match_id'])["fours"].sum()).reset_index()
inn_Sixes=pd.DataFrame(total_df.groupby(['batsmen','match_id'])["sixes"].sum()).reset_index()

In [13]:
inn_balls =pd.DataFrame(total_df.groupby(['batsmen','match_id'])["balls"].count()).reset_index()

In [14]:
inn_Dots = pd.DataFrame(total_df.groupby(['batsmen','match_id'])["dots"].sum()).reset_index()

In [15]:
inn_stats = inn_runs.merge(inn_balls, on=['batsmen','match_id']).merge(inn_Dots, on=['batsmen','match_id']).merge(inn_Ones, on=['batsmen','match_id']).merge(inn_Twos,on=['batsmen','match_id']).merge(inn_Threes, on=['batsmen','match_id']).merge(inn_Fours,on=['batsmen','match_id']).merge(inn_Sixes,on=['batsmen','match_id'])

In [16]:
inn_stats.head(5)

      batsmen  match_id  batsmen_runs  balls  dots  ones  twos  threes  fours  sixes
0  A Athanaze      2675            65     48    26     9     1       0      9      3
1  A Athanaze      2728            22     19    12     2     1       0      3      1
2  A Athanaze      2729             6      9     5     3     0       1      0      0
3  A Athanaze      2731            32     52    32    14     3       0      3      0
4     A Bagai        19             7     25    18     7     0       0      0      0

In [17]:
inn_venue =pd.DataFrame(total_df.groupby(['batsmen','match_id'])["venue"].unique()).reset_index()

In [18]:
# Strikerate = SR, Ball per boundry = BPB, last 3

In [19]:
inn_stats['inn_SR']=inn_stats.apply(lambda x: 100*(x['batsmen_runs']/x['balls']),axis=1)

In [20]:
inn_stats['inn_BPB'] = inn_stats.apply(lambda x: (x['balls']/(x['fours']+x['sixes'])) if (x["fours"]+x["sixes"])!= 0 else 0,axis=1)

In [21]:
inn_stats["last_3_inn_avg"] = (
    inn_stats.groupby("batsmen")["batsmen_runs"]
    .rolling(min_periods=1, window=3)
    .mean()
    .reset_index(level=0, drop=True))

In [22]:
inn_stats.head()

      batsmen  match_id  batsmen_runs  balls  dots  ones  twos  threes  fours  sixes      inn_SR    inn_BPB  last_3_inn_avg
0  A Athanaze      2675            65     48    26     9     1       0      9      3  135.416667   4.000000            65.0
1  A Athanaze      2728            22     19    12     2     1       0      3      1  115.789474   4.750000            43.5
2  A Athanaze      2729             6      9     5     3     0       1      0      0   66.666667   0.000000            31.0
3  A Athanaze      2731            32     52    32    14     3       0      3      0   61.538462  17.333333            20.0
4     A Bagai        19             7     25    18     7     0       0      0      0   28.000000   0.000000             7.0

In [23]:
inn_stats = inn_stats.merge(inn_venue, on=['batsmen','match_id'])

In [24]:
inn_city =pd.DataFrame(total_df.groupby(['batsmen','match_id'])["city"].unique()).reset_index()

In [25]:
inn_df = inn_stats.merge(inn_city, on=['batsmen','match_id'])

In [26]:
inn_df.head(2)

      batsmen  match_id  batsmen_runs  balls  dots  ones  twos  threes  fours  sixes      inn_SR  inn_BPB  last_3_inn_avg                                    venue          city
0  A Athanaze      2675            65     48    26     9     1       0      9      3  135.416667     4.00            65.0                [Sharjah Cricket Stadium]     [Sharjah]
1  A Athanaze      2728            22     19    12     2     1       0      3      1  115.789474     4.75            43.5  [Kensington Oval, Bridgetown, Barbados]  [Bridgetown]

## time to make career wise stats for individual players and then we will merge it

In [27]:
total_df.head(2)

   match_id        date  inning_no batting_team  over_num  balls     batsmen     bowler non_striker  batsmen_runs  extra_runs     extra_type wicket_type player_out fielder  total_runs  is_wicket                 event_name match_type gender    city                venue  overs       team_1 team_2 toss_winner toss_decision match_winner player_of_match  by_runs  by_wickets      umpire_1  umpire_2  tv_umpire reserve_umpire  match_refree  dots  ones  twos  threes  fours  sixes
0         1  2002-12-29          1  New Zealand         0      1  SP Fleming  J Srinath    NJ Astle             0           1        legbyes           0          0       0           1          0  India tour of New Zealand        ODI   male  Napier  McLean Park, Napier     50  New Zealand  India       India         field  New Zealand        V Sehwag     35.0         NaN  EAR de Silva  DB Cowie  BF Bowden            NaN  RS Madugalle     1     0     0       0      0      0
1         1  2002-12-29          1  New Zealand         0      2    NJ Astle  J Srinath  SP Fleming             0           0  fair delivery           0          0       0           0          0  India tour of New Zealand        ODI   male  Napier  McLean Park, Napier     50  New Zealand  India       India         field  New Zealand        V Sehwag     35.0         NaN  EAR de Silva  DB Cowie  BF Bowden            NaN  RS Madugalle     1     0     0       0      0      0

In [28]:
Innings = pd.DataFrame(total_df.groupby('batsmen')['match_id'].apply(lambda x: len(list(np.unique(x))))).reset_index().rename(columns={'match_id':'innings'})

In [29]:
total_balls = pd.DataFrame(total_df.groupby('batsmen')['match_id'].count()).reset_index().rename(columns={'match_id':'total_balls'})

In [30]:
total_runs = pd.DataFrame(total_df.groupby('batsmen')['batsmen_runs'].sum()).reset_index().rename(columns={'batsmen_runs':'career_runs'})

In [31]:
total_fours = pd.DataFrame(total_df.groupby('batsmen')['fours'].sum()).reset_index().rename(columns={'fours':'total_fours'})

In [32]:
total_sixes = pd.DataFrame(total_df.groupby('batsmen')['sixes'].sum()).reset_index().rename(columns={'sixes':'total_sixes'})

In [33]:
career_df = Innings.merge(total_runs, on='batsmen').merge(total_balls, on ='batsmen').merge(total_fours, on='batsmen').merge(total_sixes,on='batsmen')

In [34]:
career_df.head()

       batsmen  innings  career_runs  total_balls  total_fours  total_sixes
0   A Athanaze        4          125          128           15            4
1      A Bagai       24          614          995           63            1
2  A Balbirnie       94         2878         3855          281           35
3      A Beggs        1            0            2            0            0
4     A Bohara        2           13           14            0            0

In [35]:
# lets add strikerate , career avg, ball per boundry

In [36]:
career_df['career_SR'] = career_df.apply(lambda x: 100*(x['career_runs']/x['total_balls']),axis=1)

In [37]:
career_df['career_AVG'] = career_df.apply(lambda x: x['career_runs']/x['innings'],axis=1)

In [38]:
career_df['BPB'] = career_df.apply(lambda x: (x['total_balls']/(x['total_fours']+x['total_sixes'])) if (x['total_fours']+x['total_sixes']) != 0 else 0,axis=1)

In [39]:
career_df.head()

       batsmen  innings  career_runs  total_balls  total_fours  total_sixes  career_SR  career_AVG        BPB
0   A Athanaze        4          125          128           15            4  97.656250   31.250000   6.736842
1      A Bagai       24          614          995           63            1  61.708543   25.583333  15.546875
2  A Balbirnie       94         2878         3855          281           35  74.656291   30.617021  12.199367
3      A Beggs        1            0            2            0            0   0.000000    0.000000   0.000000
4     A Bohara        2           13           14            0            0  92.857143    6.500000   0.000000

### merging innings stats with career stats

In [40]:
full_df = inn_df.merge(career_df, on = 'batsmen')

In [41]:
full_df.head(3)

      batsmen  match_id  batsmen_runs  balls  dots  ones  twos  threes  fours  sixes      inn_SR  inn_BPB  last_3_inn_avg                                    venue          city  innings  career_runs  total_balls  total_fours  total_sixes  career_SR  career_AVG       BPB
0  A Athanaze      2675            65     48    26     9     1       0      9      3  135.416667     4.00            65.0                [Sharjah Cricket Stadium]     [Sharjah]        4          125          128           15            4   97.65625       31.25  6.736842
1  A Athanaze      2728            22     19    12     2     1       0      3      1  115.789474     4.75            43.5  [Kensington Oval, Bridgetown, Barbados]  [Bridgetown]        4          125          128           15            4   97.65625       31.25  6.736842
2  A Athanaze      2729             6      9     5     3     0       1      0      0   66.666667     0.00            31.0  [Kensington Oval, Bridgetown, Barbados]  [Bridgetown]        4          125          128           15            4   97.65625       31.25  6.736842

In [42]:
full_df['venue'] = full_df['venue'].astype(str)

In [43]:
full_df['city'] = full_df['city'].astype(str)

In [44]:
from sklearn.preprocessing import LabelEncoder

In [45]:
full_df.head()

      batsmen  match_id  batsmen_runs  balls  dots  ones  twos  threes  fours  sixes      inn_SR    inn_BPB  last_3_inn_avg                                      venue            city  innings  career_runs  total_balls  total_fours  total_sixes  career_SR  career_AVG        BPB
0  A Athanaze      2675            65     48    26     9     1       0      9      3  135.416667   4.000000            65.0                ['Sharjah Cricket Stadium']     ['Sharjah']        4          125          128           15            4  97.656250   31.250000   6.736842
1  A Athanaze      2728            22     19    12     2     1       0      3      1  115.789474   4.750000            43.5  ['Kensington Oval, Bridgetown, Barbados']  ['Bridgetown']        4          125          128           15            4  97.656250   31.250000   6.736842
2  A Athanaze      2729             6      9     5     3     0       1      0      0   66.666667   0.000000            31.0  ['Kensington Oval, Bridgetown, Barbados']  ['Bridgetown']        4          125          128           15            4  97.656250   31.250000   6.736842
3  A Athanaze      2731            32     52    32    14     3       0      3      0   61.538462  17.333333            20.0  ['Brian Lara Stadium, Tarouba, Trinidad']     ['Tarouba']        4          125          128           15            4  97.656250   31.250000   6.736842
4     A Bagai        19             7     25    18     7     0       0      0      0   28.000000   0.000000             7.0                      ['Kingsmead, Durban']      ['Durban']       24          614          995           63            1  61.708543   25.583333  15.546875

In [46]:
le = LabelEncoder()

In [47]:
full_df['venue'] = le.fit_transform(full_df['venue'])

In [48]:
full_df['city'] = le.fit_transform(full_df['city'])

In [49]:
full_df.head(3)

      batsmen  match_id  batsmen_runs  balls  dots  ones  twos  threes  fours  sixes      inn_SR  inn_BPB  last_3_inn_avg  venue  city  innings  career_runs  total_balls  total_fours  total_sixes  career_SR  career_AVG       BPB
0  A Athanaze      2675            65     48    26     9     1       0      9      3  135.416667     4.00            65.0    277   144        4          125          128           15            4   97.65625       31.25  6.736842
1  A Athanaze      2728            22     19    12     2     1       0      3      1  115.789474     4.75            43.5    164    22        4          125          128           15            4   97.65625       31.25  6.736842
2  A Athanaze      2729             6      9     5     3     0       1      0      0   66.666667     0.00            31.0    164    22        4          125          128           15            4   97.65625       31.25  6.736842

In [50]:
df_stats = full_df.copy()

In [51]:
df_stats = df_stats.drop(['batsmen','match_id'],axis=1)

In [52]:
corr = df_stats.corr()

In [53]:
corr['batsmen_runs'].sort_values(ascending=False)

batsmen_runs      1.000000
balls             0.919524
ones              0.908109
fours             0.892274
dots              0.780150
twos              0.777407
last_3_inn_avg    0.683500
sixes             0.582760
career_AVG        0.423420
inn_SR            0.387743
threes            0.353695
total_fours       0.299624
career_runs       0.296640
total_balls       0.294844
inn_BPB           0.288431
innings           0.246841
total_sixes       0.221933
career_SR         0.198055
city              0.003483
venue             0.003267
BPB              -0.143445
Name: batsmen_runs, dtype: float64

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
X = df_stats.drop(['batsmen_runs'],axis=1)
y = df_stats['batsmen_runs']

In [56]:
X_train, X_temp, y_train, y_temp = train_test_split(X,y, test_size = 0.3, random_state= 42)

In [57]:
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size = 0.5, random_state= 42)

In [58]:
print(f"Training data: {X_train.shape[0]} samples")
print(f"Validation data: {X_val.shape[0]} samples")
print(f"Testing data: {X_test.shape[0]} samples")

Training data: 33892 samples
Validation data: 7263 samples
Testing data: 7263 samples

In [59]:
from sklearn.linear_model import LinearRegression

In [60]:
lr = LinearRegression()

In [61]:
lr.fit(X_train, y_train)

LinearRegression()

In [62]:
y_pred = lr.predict(X_val)

In [63]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [64]:
mae = mean_absolute_error(y_val, y_pred)

In [65]:
mse = mean_squared_error(y_val, y_pred)

In [66]:
r2 = r2_score(y_val, y_pred)

In [67]:
rmse = np.sqrt(mse)

In [68]:
print(f"Mean Absolute Error : {mae}")
print(f"Mean Squared Error : {mse}")
print(f"Root Mean Squared Error : {rmse}")
print(f"R-squared : {r2}")

Mean Absolute Error : 0.0004650844246300861
Mean Squared Error : 5.142209397943493e-06
Root Mean Squared Error : 0.002267644019228656
R-squared : 0.9999999931178695

In [69]:
# now we need to test it in the testing data which is the unseen data

In [70]:
y_pred_test = lr.predict(X_test)

In [71]:
mae_test = mean_absolute_error(y_test, y_pred_test)

In [72]:
mse_test = mean_squared_error(y_test, y_pred_test)

In [73]:
r2_test = r2_score(y_test, y_pred_test)

In [74]:
rmse_test = np.sqrt(mse_test)

In [75]:
print(f"Mean Absolute Error test : {mae_test}")
print(f"Mean Squared Error test: {mse_test}")
print(f"Root Mean Squared Error test: {rmse_test}")
print(f"R-squared test: {r2_test}")

Mean Absolute Error test : 0.0003724753650323174
Mean Squared Error test: 2.6100272403713555e-06
Root Mean Squared Error test: 0.0016155578728016386
R-squared test: 0.9999999966404212

### Lets make the predictions

In [82]:
# Using virat kohli's ODI Stats

In [83]:
full_df.head()

      batsmen  match_id  batsmen_runs  balls  dots  ones  twos  threes  fours  sixes      inn_SR    inn_BPB  last_3_inn_avg  venue  city  innings  career_runs  total_balls  total_fours  total_sixes  career_SR  career_AVG        BPB
0  A Athanaze      2675            65     48    26     9     1       0      9      3  135.416667   4.000000            65.0    277   144        4          125          128           15            4  97.656250   31.250000   6.736842
1  A Athanaze      2728            22     19    12     2     1       0      3      1  115.789474   4.750000            43.5    164    22        4          125          128           15            4  97.656250   31.250000   6.736842
2  A Athanaze      2729             6      9     5     3     0       1      0      0   66.666667   0.000000            31.0    164    22        4          125          128           15            4  97.656250   31.250000   6.736842
3  A Athanaze      2731            32     52    32    14     3       0      3      0   61.538462  17.333333            20.0     52   152        4          125          128           15            4  97.656250   31.250000   6.736842
4     A Bagai        19             7     25    18     7     0       0      0      0   28.000000   0.000000             7.0    168    59       24          614          995           63            1  61.708543   25.583333  15.546875

In [85]:
vk =full_df[full_df.batsmen == 'V Kohli']

In [86]:
vk_df = vk.drop(['batsmen','match_id','batsmen_runs'],axis=1)

In [87]:
Predictions = lr.predict(vk_df)

In [90]:
vk_df['Predicted_runs'] = Predictions

In [92]:
vk_df

       balls  dots  ones  twos  threes  fours  sixes      inn_SR    inn_BPB  last_3_inn_avg  venue  city  innings  career_runs  total_balls  total_fours  total_sixes  career_SR  career_AVG        BPB  Predicted_runs
46041     22    16     3     1       1      1      0   54.545455  22.000000       12.000000    250   167      270        13223        14394         1239          144  91.864666   48.974074  10.407809       11.999682
46042     69    52     9     2       0      6      0   53.623188  11.500000       24.500000    250   167      270        13223        14394         1239          144  91.864666   48.974074  10.407809       37.000000
46043     41    32     3     0       2      4      0   60.975610  10.250000       24.666667    243    42      270        13223        14394         1239          144  91.864666   48.974074  10.407809       25.000248
46044     66    43     8     6       2      7      0   81.818182   9.428571       38.666667    243    42      270        13223        14394         1239          144  91.864666   48.974074  10.407809       54.000519
46045     47    34     5     4       0      3      1   65.957447  11.750000       36.666667    243    42      270        13223        14394         1239          144  91.864666   48.974074  10.407809       31.000056
46046      2     0     2     0       0      0      0  100.000000   0.000000       29.000000    243    42      270        13223        14394         1239          144  91.864666   48.974074  10.407809        1.999312
46047     24    12    10     1       0      1      0   66.666667  24.000000       16.333333    305    32      270        13223        14394         1239          144  91.864666   48.974074  10.407809       15.999015
46048    107    71    19     6       0      9      2   73.831776   9.727273       32.333333    212    86      270        13223        14394         1239          144  91.864666   48.974074  10.407809       79.000490
46049     42    21    18     0       0      3      0   71.428571  14.000000       41.666667    253   160      270        13223        14394         1239          144  91.864666   48.974074  10.407809       29.998975
46050     17    10     6     0       0      1      0   58.823529  17.000000       39.666667    239    33      270        13223        14394         1239          144  91.864666   48.974074  10.407809        9.999119
46051     19     7     5     3       0      4      0  142.105263   4.750000       22.333333    178   139      270        13223        14394         1239          144  91.864666   48.974074  10.407809       26.999329
46052     65    34    22     2       0      7      0   83.076923   9.285714       30.333333    338   118      270        13223        14394         1239          144  91.864666   48.974074  10.407809       53.999126
46053    119    54    49     4       0     11      1   89.915966   9.916667       62.666667    103    99      270        13223        14394         1239          144  91.864666   48.974074  10.407809      106.998757
46054     12     6     5     0       0      1      0   75.000000  12.000000       56.666667    283   114      270        13223        14394         1239          144  91.864666   48.974074  10.407809        8.999136
46055    107    48    41    11       0      7      0   85.046729  15.285714       69.000000    283   114      270        13223        14394         1239          144  91.864666   48.974074  10.407809       90.999199
46056     69    33    21     4       2      9      0  102.898551   7.666667       57.000000    283   114      270        13223        14394         1239          144  91.864666   48.974074  10.407809       70.999699
46057     95    36    39     8       1     11      0  107.368421   8.636364       88.000000    283   114      270        13223        14394         1239          144  91.864666   48.974074  10.407809      101.998988
46058      8     7     0     1       0      0      0   25.000000   0.000000       58.333333    283   114      270        13223        14394         1239          144  91.864666   48.974074  10.407809        1.999572
46059     46    19    25     1       0      1      0   67.391304  46.000000       45.000000    265    83      270        13223        14394         1239          144  91.864666   48.974074  10.407809       30.998389
46060     71    34    29     3       0      4      1   80.281690  14.200000       30.000000    262     5      270        13223        14394         1239          144  91.864666   48.974074  10.407809       56.999148
46061     93    37    42     8       1      4      0   88.172043  23.250000       56.666667    240    26      270        13223        14394         1239          144  91.864666   48.974074  10.407809       82.025116
46062     29    16    10     2       0      1      0   62.068966  29.000000       52.333333    131   167      270        13223        14394         1239          144  91.864666   48.974074  10.407809       17.999107
46063     95    49    34     7       0      5      0   71.578947  19.000000       56.000000    131   167      270        13223        14394         1239          144  91.864666   48.974074  10.407809       67.999313
46064     22    13     7     2       0      0      0   50.000000   0.000000       32.333333    250   167      270        13223        14394         1239          144  91.864666   48.974074  10.407809       10.999586
46065     27    15     8     3       0      1      0   66.666667  27.000000       32.333333    250   167      270        13223        14394         1239          144  91.864666   48.974074  10.407809       17.999243
46066     14     9     3     0       1      1      0   71.428571  14.000000       13.000000    250   167      270        13223        14394         1239          144  91.864666   48.974074  10.407809        9.999577
46067     34    19    10     1       0      4      0   82.352941   8.500000       18.666667    250   167      270        13223        14394         1239          144  91.864666   48.974074  10.407809       27.999291
46068      3     3     0     0       0      0      0    0.000000   0.000000       12.666667    250   167      270        13223        14394         1239          144  91.864666   48.974074  10.407809       -0.000519
46069     16    12     2     1       0      1      0   50.000000  16.000000       12.000000    250   167      270        13223        14394         1239          144  91.864666   48.974074  10.407809        7.999425
46070     57    40     8     3       1      5      0   64.912281  11.400000       15.000000    250   167      270        13223        14394         1239          144  91.864666   48.974074  10.407809       37.000140
46071    125    53    52     8       0     11      1   94.400000  10.416667       54.333333     99   161      270        13223        14394         1239          144  91.864666   48.974074  10.407809      117.998868
46072    107    45    42     7       3     10      0   98.130841  10.700000       86.666667    209    72      270        13223        14394         1239          144  91.864666   48.974074  10.407809      104.999611
46073     73    39    20     6       0      8      0   87.671233   9.125000       95.666667    265    83      270        13223        14394         1239          144  91.864666   48.974074  10.407809       63.999404
46074     73    40    23     2       0      6      2   86.301370   9.125000       77.333333    253   160      270        13223        14394         1239          144  91.864666   48.974074  10.407809       62.999559
46075      3     3     0     0       0      0      0    0.000000   0.000000       42.333333    172    11      270        13223        14394         1239          144  91.864666   48.974074  10.407809       -0.000592
46076      8     7     0     1       0      0      0   25.000000   0.000000       21.666667    176    36      270        13223        14394         1239          144  91.864666   48.974074  10.407809        1.999586
46077     72    33    32     4       0      2      1   75.000000  24.000000       18.666667    167    59      270        13223        14394         1239          144  91.864666   48.974074  10.407809       53.999073
46078     34    21     6     6       0      1      0   64.705882  34.000000       26.000000    212    86      270        13223        14394         1239          144  91.864666   48.974074  10.407809       21.999492
46079     42    30     6     1       0      5      0   66.666667   8.400000       34.666667    214    30      270        13223        14394         1239          144  91.864666   48.974074  10.407809       27.999571
46080     92    44    31     8       0      7      2   94.565217  10.222222       45.666667     11   130      270        13223        14394         1239          144  91.864666   48.974074  10.407809       86.999678
46081      6     4     2     0       0      0      0   33.333333   0.000000       39.000000    305    32      270        13223        14394         1239          144  91.864666   48.974074  10.407809        1.999379
46082     86    29    39     7       1      8      2  116.279070   8.600000       63.000000    283   114      270        13223        14394         1239          144  91.864666   48.974074  10.407809       99.999242
46083      5     1     2     1       0      1      0  160.000000   5.000000       36.666667    172    11      270        13223        14394         1239          144  91.864666   48.974074  10.407809        7.999270
46084     54    29    22     0       0      3      0   62.962963  18.000000       47.333333    172    11      270        13223        14394         1239          144  91.864666   48.974074  10.407809       33.998929
46085     20    15     2     1       0      2      0   60.000000  10.000000       18.000000    112    48      270        13223        14394         1239          144  91.864666   48.974074  10.407809       11.999494
46086      3     2     1     0       0      0      0   33.333333   0.000000       15.666667    338   118      270        13223        14394         1239          144  91.864666   48.974074  10.407809        0.999411
46087     78    36    35     2       0      5      0   75.641026  15.600000       24.000000    176    36      270        13223        14394         1239          144  91.864666   48.974074  10.407809       58.998749
46088     33    13    18     1       0      1      0   72.727273  33.000000       28.000000    262     5      270        13223        14394         1239          144  91.864666   48.974074  10.407809       23.998643
46089     21    12     9     0       0      0      0   42.857143   0.000000       30.666667    239    33      270        13223        14394         1239          144  91.864666   48.974074  10.407809        8.999353
46090     52    33    11     4       0      4      0   67.307692  13.000000       22.666667    342   117      270        13223        14394         1239          144  91.864666   48.974074  10.407809       34.999657
46091      8     6     2     0       0      0      0   25.000000   0.000000       15.333333      7   158      270        13223        14394         1239          144  91.864666   48.974074  10.407809        1.999495
46092    106    54    39     6       0      6      1   76.415094  15.142857       39.333333      7   158      270        13223        14394         1239          144  91.864666   48.974074  10.407809       80.999391
46093      1     1     0     0       0      0      0    0.000000   0.000000       27.666667    291     8      270        13223        14394         1239          144  91.864666   48.974074  10.407809       -0.000630
46094     33    16    15     0       1      1      0   66.666667  33.000000       34.333333    291     8      270        13223        14394         1239          144  91.864666   48.974074  10.407809       21.999026
46095    107    48    44     5       0     10      0   87.850467  10.700000       38.666667    259    84      270        13223        14394         1239          144  91.864666   48.974074  10.407809       93.998728
46096     74    34    33     3       0      4      0   74.324324  18.500000       57.000000    254    37      270        13223        14394         1239          144  91.864666   48.974074  10.407809       54.998794
46097      9     2     5     2       0      0      0  100.000000   0.000000       52.666667    314   146      270        13223        14394         1239          144  91.864666   48.974074  10.407809        8.999375
46098     18    13     3     2       0      0      0   38.888889   0.000000       23.666667    160   107      270        13223        14394         1239          144  91.864666   48.974074  10.407809        6.999705
46099     39    28     8     2       0      1      0   41.025641  39.000000       10.666667      2   107      270        13223        14394         1239          144  91.864666   48.974074  10.407809       15.999336
46100     93    34    35    12       2      9      1  115.053763   9.300000       43.333333    293    31      270        13223        14394         1239          144  91.864666   48.974074  10.407809      106.999811
46101     63    30    29     4       0      0      0   58.730159   0.000000       53.333333    248    81      270        13223        14394         1239          144  91.864666   48.974074  10.407809       36.999337
46102    104    45    39     3       1     16      0  107.692308   6.500000       85.333333    112    48      270        13223        14394         1239          144  91.864666   48.974074  10.407809      111.998715
46103     30    14     8     2       1      5      0  116.666667   6.000000       61.333333    239    33      270        13223        14394         1239          144  91.864666   48.974074  10.407809       34.999479
46104     99    49    36     3       0     11      0   86.868687   9.000000       77.666667    342   117      270        13223        14394         1239          144  91.864666   48.974074  10.407809       85.998849
46105      5     5     0     0       0      0      0    0.000000   0.000000       40.333333    103    99      270        13223        14394         1239          144  91.864666   48.974074  10.407809       -0.000514
46106      7     5     1     1       0      0      0   42.857143   0.000000       29.666667     30    44      270        13223        14394         1239          144  91.864666   48.974074  10.407809        2.999510
46107    127    56    53     4       0     14      0   92.125984   9.071429       40.000000     99   161      270        13223        14394         1239          144  91.864666   48.974074  10.407809      116.998433
46108     30    20     6     1       0      3      0   66.666667  10.000000       46.666667    262     5      270        13223        14394         1239          144  91.864666   48.974074  10.407809       19.999391
46109     13     3     3     4       0      3      0  176.923077   4.333333       53.333333    139    82      270        13223        14394         1239          144  91.864666   48.974074  10.407809       22.999367
46110     86    27    48     6       0      5      0   93.023256  17.200000       41.000000    176    36      270        13223        14394         1239          144  91.864666   48.974074  10.407809       79.998297
46111     34    18     8     4       1      3      0   91.176471  11.333333       44.666667    195   167      270        13223        14394         1239          144  91.864666   48.974074  10.407809       30.999754
46112     94    50    31     4       0      8      1   81.914894  10.444444       62.666667    347   127      270        13223        14394         1239          144  91.864666   48.974074  10.407809       76.999376
46113     28    15    11     0       1      1      0   64.285714  28.000000       42.000000     14   167      270        13223        14394         1239          144  91.864666   48.974074  10.407809       17.999250
46114     25    14     9     1       0      1      0   60.000000  25.000000       36.666667     14   167      270        13223        14394         1239          144  91.864666   48.974074  10.407809       14.999112
46115     25    16     7     1       1      0      0   48.000000   0.000000       15.000000     54    24      270        13223        14394         1239          144  91.864666   48.974074  10.407809       11.999858
46116     83    35    34    12       0      2      0   79.518072  41.500000       31.000000     54    24      270        13223        14394         1239          144  91.864666   48.974074  10.407809       65.999070
46117     27    14     9     2       0      2      0   77.777778  13.500000       33.000000    307   167      270        13223        14394         1239          144  91.864666   48.974074  10.407809       20.999270
46118     91    26    37    10       0     16      2  146.153846   5.055556       73.333333     39    78      270        13223        14394         1239          144  91.864666   48.974074  10.407809      132.998779
46119    122    46    58    11       0      7      0   88.524590  17.428571       87.333333    283   114      270        13223        14394         1239          144  91.864666   48.974074  10.407809      107.998561
46120     82    34    40     3       0      5      0   80.487805  16.400000      102.333333    283   114      270        13223        14394         1239          144  91.864666   48.974074  10.407809       65.998532
46121    151    58    56    12       1     22      2  121.192053   6.291667      119.000000    283   114      270        13223        14394         1239          144  91.864666   48.974074  10.407809      182.998951
46122    113    45    50     7       2      9      0   93.805310  12.555556      118.333333    181    75      270        13223        14394         1239          144  91.864666   48.974074  10.407809      105.999071
46123      5     4     1     0       0      0      0   20.000000   0.000000       96.666667    181    75      270        13223        14394         1239          144  91.864666   48.974074  10.407809        0.999372
46124     69    41    22     4       0      2      0   55.072464  34.500000       48.333333    243    42      270        13223        14394         1239          144  91.864666   48.974074  10.407809       37.999248
46125    121    50    46    11       0     12      2  105.785124   8.642857       55.666667    243    42      270        13223        14394         1239          144  91.864666   48.974074  10.407809      127.999236
46126     36    23     7     4       0      2      0   63.888889  18.000000       63.000000    232   167      270        13223        14394         1239          144  91.864666   48.974074  10.407809       22.999560
46127      5     5     0     0       0      0      0    0.000000   0.000000       50.333333    176    36      270        13223        14394         1239          144  91.864666   48.974074  10.407809       -0.000545
46128      9     7     0     1       0      1      0   66.666667   9.000000        9.666667    103    99      270        13223        14394         1239          144  91.864666   48.974074  10.407809        5.999457
46129     18    14     3     0       0      1      0   38.888889  18.000000        4.333333    112    48      270        13223        14394         1239          144  91.864666   48.974074  10.407809        6.999333
46130     22    10    11     0       0      1      0   68.181818  22.000000        9.333333    263   139      270        13223        14394         1239          144  91.864666   48.974074  10.407809       14.998952
46131     55    27    25     1       0      1      1   67.272727  27.500000       19.666667    209    98      270        13223        14394         1239          144  91.864666   48.974074  10.407809       36.999008